### ISSUE TITLE
Error: Unknown option: --name

### ISSUE THREAD

**Issue by seanidzenga** [wiverson/jtoolprovider-plugin#1]
I'm trying to use this tool much in the same way as the example found here: https://github.com/wiverson/maven-jpackage-template/blob/main/pom.xml to run jlink to build a runtime image

I keep receiving an error stating that there's no such option as `--name` (which is correct, jlink doesn't have a name argument)

my configuration isn't even all that different from the example provided:

```
<plugin>
    <groupId>io.github.wiverson</groupId>
    <artifactId>jtoolprovider-plugin</artifactId>
    <version>1.0.34</version>
    <executions>
        <execution>
            <id>jlink</id>
            <phase>package</phase>
            <goals>
                <goal>java-tool</goal>
            </goals>
            <configuration>
                <toolName>jlink</toolName>
                <removeDirectories>${project.build.directory}/jvm-image</removeDirectories>
                <addModules>${jvm.modules}</addModules>
                <modulePath>${project.build.directory}/dependency</modulePath>
                <output>${project.build.directory}/jvm-image</output>
                <args>
                    <arg>--strip-native-commands</arg>
                    <arg>--no-header-files</arg>
                    <arg>--strip-debug</arg>
                    <arg>--no-man-pages</arg>
                    <arg>--compress=2</arg>
                </args>
            </configuration>
        </execution>
    </executions>
</plugin>
```

I'm running an older jdk, version 11.0.10 if that helps

**Comment by wiverson** [comment]
I have only been supporting / testing on JDK 16, not sure if jlink is exposed to the ToolProvider API on 11. The tool name (jlink) is passed to the JDK ToolProvider API to invoke it.

If jlink is on your path but not working as a ToolProvider I would suggest looking at https://www.mojohaus.org/exec-maven-plugin/ to invoke jlink.

FWIW if you can I would just upgrade to JDK 16. If you have control over your JVM install anyways might as well be current.

**Comment by seanidzenga** [comment]
unfortunately my hands are tied with which JDK I use, stuck with latest LTS until I get permission to upgrade.

It's not the `<toolName>` parameter that's failing, in fact it finds and runs jlink just fine but it's adding a `--name` parameter to the command-line and adding the project `<name>` value after it, so something like 

```
jlink --name My Super Cool Project --addModules foo.bar,bar.foo,foobar.foo --output C:\workspace\supahcool\target\jvm-image
```

Either way, yeah good call on using maven-exec, works like a charm.

**Comment by wiverson** [comment]
Not sure where the --name is coming from, nothing in the plugin code is adding it AFAIK.

**Comment by seanidzenga** [comment]
Yeah it's a weird one, I might poke at it more later and see where I messed up (aside from using the wrong jdk version, which very well could be it) thanks for the quick reply!
