### ISSUE TITLE
Customizing Wix

### ISSUE THREAD

**Issue by hrzafer** [wiverson/jtoolprovider-plugin#9]
Hi, 

I am trying to customize my Windows installer. [Here](https://docs.oracle.com/en/java/javase/16/jpackage/override-jpackage-resources.html#GUID-1B718F8B-B68D-4D46-B1DB-003D7729AAB6) it says, we can use `--resource-dir` to tell `jpackage` to override some of the Wix configuration.  I tried passing that option into the `win-packages.txt` file as 
```
--resource-dir  ${project.build.directory}\packaging
```

and creating a `main.wxs` file under `src/packaging`. However, it still uses the `main.wxs` created under `target/installer-work/config`.  Does this plugin directly or indirectly support this kind of customization?

Thanks.

**Comment by wiverson** [comment]
The plugin just calls jpackage via a JDK supplied API (as opposed to, say, kicking it off via the command line).

I haven't messed around with actually using that customization. From the jpackage docs looks like --verbose and --temp are helpful for debugging. It kind of looks like the process is to use --temp to generate the default file directory structure, then drop in override files, and then run jpackage again...?

The plugin should be perfectly happy running jpackage command. Depending on your Maven expertise, you might want to try:

- running jpackage with --temp to get a working file set
- drop an updated main.wxs into that directory
- run jpackage a second time with --resource-dir pointing at the temp directory

You could absolutely do all that via the plugin and a resources plugin execution. How is your Maven? ;)
